### ISSUE TITLE
set the inital screensize

### ISSUE THREAD

**Issue by sowiso** [partridgejiang/Kekule.js#216]
Is there a way to set the inital screen size of the composer to something else than the default value?

**Comment by partridgejiang** [comment]
Hi @sowiso, you can simply use the CSS to control the size of composer (and other widgets), e.g.:
```css
#myComposer
{
  width: 800px;
  height: 600px;
}
```
In JavaScript, the ```setDimension``` method can be used as well:
```js
composer.setDimension('800px', '600px');
```
